// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLbU1hjzQ_7RA2IKuxDwNymK4wJeYf6c',
    appId: '1:1054085078088:android:fbf0b8f8ab2822b51c8c7d',
    messagingSenderId: '1054085078088',
    projectId: 'coin-watcher-c76e3',
    storageBucket: 'coin-watcher-c76e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAwctiA_Gs7T51bXdnEZN-PwTGBigggsw',
    appId: '1:1054085078088:ios:916d48a72e22ef761c8c7d',
    messagingSenderId: '1054085078088',
    projectId: 'coin-watcher-c76e3',
    storageBucket: 'coin-watcher-c76e3.firebasestorage.app',
    iosClientId: '1054085078088-arc92sgv1v8164h1re9kujufb9e3v1sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinWatcher',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAe9aujoLcYZZynXs7UgRrHaSFbkGvJE',
    appId: '1:1054085078088:web:c90f0195fbd10a0e1c8c7d',
    messagingSenderId: '1054085078088',
    projectId: 'coin-watcher-c76e3',
    authDomain: 'coin-watcher-c76e3.firebaseapp.com',
    storageBucket: 'coin-watcher-c76e3.firebasestorage.app',
    measurementId: 'G-J3RX8GG6RR',
  );

}